project:
  type: book

execute:
  freeze: auto
  
  
book:
  title: "From Data to Design"
  output-file: "FromDatatoDesign2026"
  subtitle: "Using Big Data for Active Mobility Research"
  author: 
    - name: "Gabriel Valença"
      email: gabrielvalenca@tecnico.pt
      url: https://ushift.tecnico.ulisboa.pt/team-gabriel-valenca/
      orcid: 0000-0002-3684-3005
      affiliation: "Instituto Superior Técnico - University of Lisbon"
    - name: "Avital Angel"
      email: avital.angel@tum.de
      url: https://www.mos.ed.tum.de/en/sv/about-us/team/dr-avital-angel/
      orcid: 0000-0001-5005-0100
      affiliation: "Technical University of Munich"
  date: today
  # date-modified: today
  chapters:
    - index.qmd
    - structure.qmd
    - part: "**Day 1**"
      chapters:
      - software.qmd
    - about.qmd
  
  repo-url: https://github.com/valenca13/EIT_Course_BigData
  favicon: /images/favicon.png
  # sidebar:
    # tools:
      # - icon: download
      #   # href: https://github.com/U-Shift/EITcourse/releases/download/2024.09/EITcourse_GetYourDatasetReady2024.pdf
      #   # text: "Download PDF"
      #   target: _blank
  page-footer:
    left: "G Valença, A Angel"
    center: "From Data to Design: Using Big Data for Active Mobility Research"
    right: "June 2026"
    

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    code-fold: show
    code-tools: true
    number-depth: 3
    toc-expand: 3
  # pdf:
  #   documentclass: scrreprt
  #   # engine: knitr
  #   toc: true
  #   number-depth: 3
  #   toc-depth: 3
  #   # cover-image: images/cover.png # not working
  #   output-ext:  "pdf"
# prefer-html: true
    
editor: visual

google-scholar: true